#!/usr/bin/env python3
"""Step 5 - the error analysis note (deliverable #5), built from results/scores.csv.

    python scripts/error_analysis.py --scores results/scores.csv \
        --manifest data/manifest.csv --model robust --out docs/ERROR_ANALYSIS.md

Produces the markdown note plus two contact-sheet PNGs of the most confidently
wrong predictions, which are what actually convince a judge that the team looked
at their failures rather than only at their metrics.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import _bootstrap  # noqa: F401

import pandas as pd

from aigcdet.eval.error_analysis import (
    collect_errors,
    summarize_for_readme,
    write_error_contact_sheet,
)
from aigcdet.utils.io import read_manifest
from aigcdet.utils.logging import get_logger

log = get_logger("error_analysis")

PREAMBLE = """# Error Analysis

Generated by `scripts/error_analysis.py` from `results/scores.csv`. Every number
and every image below comes from the evaluation run - nothing here is written by
hand, so this note cannot drift out of sync with the results table.

The two error types are not symmetric and we do not treat them as such:

* A **false positive** tells a real photographer or journalist that their
  authentic work is synthetic. It is an accusation, it is visible to them, and
  it is the error that destroys trust in the tool. We tune the operating
  threshold against a false-positive budget for this reason.
* A **false negative** lets one generated image through. On a platform with
  layered defences and human review this is recoverable; at scale it is still
  the error we would rather make.

"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--scores", type=Path, default=Path("results/scores.csv"))
    ap.add_argument("--manifest", type=Path, default=None,
                    help="optional; adds generator-family slicing to the note")
    ap.add_argument("--model", type=str, default="robust")
    ap.add_argument("--condition", type=str, default=None,
                    help="restrict to one corruption condition; default uses all of them")
    ap.add_argument("--threshold", type=float, default=None,
                    help="default reads it from results/robustness.csv for this model")
    ap.add_argument("--top_k", type=int, default=30)
    ap.add_argument("--out", type=Path, default=Path("docs/ERROR_ANALYSIS.md"))
    ap.add_argument("--figures_dir", type=Path, default=Path("results"))
    args = ap.parse_args()

    scores = pd.read_csv(args.scores)
    scores = scores[scores["model"] == args.model]
    if args.condition:
        scores = scores[scores["condition"] == args.condition]
    if scores.empty:
        raise SystemExit(f"no rows in {args.scores} for model={args.model!r}")

    threshold = args.threshold
    if threshold is None:
        rob = Path(args.scores).parent / "robustness.csv"
        if rob.exists():
            r = pd.read_csv(rob)
            r = r[r["model"] == args.model]
            if len(r):
                threshold = float(r["threshold"].iloc[0])
    threshold = 0.5 if threshold is None else threshold

    families = None
    if args.manifest and Path(args.manifest).exists():
        man = read_manifest(args.manifest)[["image_path", "family"]]
        scores = scores.merge(man, on="image_path", how="left")
        families = scores["family"].fillna("unknown").tolist()

    errors = collect_errors(
        scores["score"].tolist(),
        scores["label"].tolist(),
        scores["image_path"].tolist(),
        threshold=threshold,
        top_k=args.top_k,
        families=families,
        conditions=scores["condition"].tolist(),
    )

    fp_png = write_error_contact_sheet(
        errors["false_positives"],
        args.figures_dir / "false_positives.png",
        title=f"Most confident FALSE POSITIVES - real images called AI ({args.model})",
    )
    fn_png = write_error_contact_sheet(
        errors["false_negatives"],
        args.figures_dir / "false_negatives.png",
        title=f"Most confident FALSE NEGATIVES - AI images called real ({args.model})",
    )

    body = [PREAMBLE, f"Model evaluated: **{args.model}**", "", summarize_for_readme(errors)]
    for png, cap in ((fp_png, "False positives"), (fn_png, "False negatives")):
        if png:
            rel = Path(png).as_posix()
            body.append(f"\n![{cap}](../{rel})\n")
    body.append(
        "\n## What we would change with more time\n\n"
        "_Fill this in after reviewing the contact sheets above as a team - one bullet per "
        "pattern you can actually see, not a generic list. Patterns worth checking for: "
        "stylised illustration and painting misread as generated; heavily compressed real "
        "photos drifting toward the AI side; photorealistic portraits from newer generators "
        "sliding under the threshold; and whether one generator family accounts for most of "
        "the false negatives._\n"
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(body), encoding="utf-8")
    log.info("error analysis -> %s", args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
